services:
  nginx:
    image: nginx:latest
    container_name: nginx_bla
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: .
    container_name: app_bla
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      PHP_LOG_DIR: /var/www/html/logs

  db:
    container_name: db_bla
    image: mariadb
    restart: always
    ports:
      - 3320:3306
    volumes:
      - ./mysqlDb:/var/lib/mysql
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
