<?php
/**
 * Created by PhpStorm.
 * User: Bogdan
 * Date: 28.07.2016
 * Time: 14:53
 */

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Category;
use common\models\Offer;
use common\models\User;

/**
 * Menu controller
 *
 * Class MenuController
 * @package frontend\controllers
 */
class MenuController extends Controller
{
    public $category;
    public $count_orders;
    public $get_orders;
    public $send_offers;
    public $accepted_offers;
    public $count_feedback;

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->category = Category::find()->all();
        if (!Yii::$app->user->isGuest) {

            $this->count_feedback = Yii::$app->user->identity->countComment;
            if (Yii::$app->user->identity->role == User::ROLE_SELLER) {
                $this->count_orders = Yii::$app->user->identity->activeOrderSeller(Yii::$app->user->id);
                $this->send_offers = Yii::$app->user->identity->getWaitingOffer()->count();
                $this->accepted_offers = Offer::find()->where(['userID' => Yii::$app->user->id])->andWhere('accepted <> ""')->andWhere('status IS NULL')->count();
            }
            if (Yii::$app->user->identity->role == User::ROLE_USER) {
                $this->count_orders = Yii::$app->user->identity->activeOrderUser()->count();
                $this->accepted_offers = count(Yii::$app->user->identity->userAcceptedOffers);
            }
        }
    }

    public function beforeAction($action) {
        if ($action->id === 'get-sub-menu') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    /**
     * Ajax sub menu page
     *
     * @param integer $id
     * @return mixed
     */
    public function actionSubMenu($id) {
        $this->layout = false;
        $breadcrumb = $this->categoryBreadcrumb($id);
        return $this->render('sub-menu', ['id' => $id, 'breadcrumb' => $breadcrumb]);
    }

    public function categoryBreadcrumb($id, $breadcrumb = array())
    {
        if ($id && $id != 0) {
            $category = Category::findOne(['ID' => $id]);
            $breadcrumb[] = $category->name;

            return $this->categoryBreadcrumb($category->parentID, $breadcrumb);
        } else {
            return implode(' / ', array_reverse($breadcrumb));
        }
    }

    public function actionGetSubMenu() {
        if ($_POST) {
            $catSub = Category::find()->where(['parentID' => $_POST['ID']])->all();

            if ($catSub) {
        ?>

            <div class="menu sub-menu">
                <div class="back-menu"><?= Yii::t('app', 'Назад'); ?></div>
                <div class="inner">
                    <?php foreach ($catSub as $category_item) : ?>
                        <?php $catSub = Category::find()->where(['parentID' => $category_item->id])->all(); ?>
                        <div class="menu-item <?= (!empty(array_filter($catSub))) ? 'icon' : ''; ?>">
                            <a href="/site/filter?id=<?= $category_item->id ?>" data-id="<?= $category_item->id ?>"><?= $category_item->name ?></a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

        <?php
            }
        }
    }
}