<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detaild description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'sourcePath' => '@frontend',
    'messagePath' => '@common/messages',
   'languages' => [    'ua-UA',  // Україна – українська    'ru-RU',  // Росія – російська    'pl-PL',  // Польща – польська    'cz-CZ',  // Чехія – чеська    'en-EN',  // Загальна англійська (для більшості країн)    'ru-KZ',  // Казахстан – російська    'en-NG',  // Нігерія – англійська    'en-IN',  // Індія – англійська    'en-AE',  // ОАЕ – англійська    'en-EG',  // Єгипет – англійська    'en-KW',  // Кувейт – англійська    'en-QA',  // Катар – англійська    'en-SA',  // Саудівська Аравія – англійська    'en-ZA',  // Південна Африка – англійська],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => true,
    'removeUnused' => false,
    'markUnused' => true,
    'ignoreCategories' => [
        'yii',
    ],
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',
];
