name: Laravel Deployment
on:
    push:
        branches:
            - develop
            - master

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Deploy to development
              if: github.ref == 'refs/heads/develop'
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: "${{ secrets.DEV_HOST }}"
                  username: "${{ secrets.DEV_USERNAME }}"
                  password: "${{ secrets.DEV_PASSWORD }}"
                  port: "${{ secrets.DEV_PORT }}"
                  script: |
                      cd /var/www/blabla
                      git fetch origin
                      git reset --hard origin/develop
                      git clean -fd 
                      git pull origin develop --force

            - name: Deploy to production
              if: github.ref == 'refs/heads/master'
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: "${{ secrets.HOST }}"
                  username: "${{ secrets.USERNAME }}"
                  password: "${{ secrets.PASSWORD }}"
                  script: |
                      cd /home/maste103/master5.kiev.ua/www
                      git pull origin master --force

            - name: Send Telegram message
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
              uses: appleboy/telegram-action@v0.1.0
              with:
                  to: "${{ secrets.TELEGRAM_ID }}"
                  token: "${{ secrets.TELEGRAM_TOKEN }}"
                  message: |
                      Deployment successful BlaBlaPrice on branch ${{ github.ref }}
